plugin: amazon.aws.aws_ec2

regions:
  - "{{ lookup('env', 'AWS_REGION') | default('us-east-1', true) }}"

filters:
  tag:Project: aws-wordpress-migration
  tag:Environment: "{{ lookup('env', 'TARGET_ENVIRONMENT') }}"
  tag:Role: wordpress-app
  instance-state-name: running

hostnames:
  - instance-id

compose:
  ansible_connection: "'amazon.aws.aws_ssm'"
  ansible_aws_ssm_region: "lookup('env', 'AWS_REGION') | default('us-east-1', true)"
  ansible_aws_ssm_bucket_name: "lookup('env', 'ANSIBLE_TRANSFER_BUCKET')"

groups:
  wordpress: true