aws_region: us-east-1

project_name: aws-wordpress-migration

db_name: company_db

migration_backup_key: wordpress.sql
wordpress_files_backup_key: wordpress-files.tar.gz

wordpress_install_dir: /var/www/html
